// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0i3Rq0beyHKfPy7eOpkevEgnB3EMK16w',
    appId: '1:688076031401:web:0f503c5a6e26a474ce30b8',
    messagingSenderId: '688076031401',
    projectId: 'medsync2025',
    authDomain: 'medsync2025.firebaseapp.com',
    storageBucket: 'medsync2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIv6-LBKwYfFg8mEvEbYikIwfPSRVt8xQ',
    appId: '1:688076031401:android:c735766491dc97bfce30b8',
    messagingSenderId: '688076031401',
    projectId: 'medsync2025',
    storageBucket: 'medsync2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYn5Fd_o5loNYhDuPodHr-6SoJKvQBJOM',
    appId: '1:688076031401:ios:19854021e8bb834cce30b8',
    messagingSenderId: '688076031401',
    projectId: 'medsync2025',
    storageBucket: 'medsync2025.firebasestorage.app',
    iosBundleId: 'com.example.medSync',
  );
}
